---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---


```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")
```


```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```


```{r}
# 加總向量內的所有元素值。
sum(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```

```{r}
class(studentMajors)
```

```{r}
typeof(studentMajors)
```

```{r}
studentMajors <- 
  c("經濟系", "經濟系", "法律系")

```

```{r}
class(studentMajors)
```

```{r}
birthplaces <- factor(
  c("台北市","台北市", "台北市","台中市","台中市")
)
```

```{r}
class(birthplaces)
```

```{r}
typeof(birthplaces)
```

```{r}
levels(birthplaces)
```

```{r}
birthplaces
```


```{r}
as.integer(birthplaces)
```


```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```

```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```


```{r}
dtObjectVector<-ymd_hms(c("1970-01-01 00:02:53","1980-02-11 11:25:22"))
```


```{r}
class(dtObjectVector)
```


```{r}
as.double(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```


```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
```

```{r}
library(stringr)
```


```{r}
course <- c("個體經濟學","投資學","總體經濟學")
str_subset(course,"經濟學")
str_detect(course,"經濟學")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
str_sub(studentID,2,4)
str_sub(studentID,5,6)
```
```{r}
year <- c("101","105","109")
month <- c("3","1","9")
day <- c("11","5","7")
char1 <- c("年","年","年")
char2 <- c("月","月","月")
char3 <- c("日","日","日")
year
char1
month
char2
day 
char3
str_c(year,char1,month,char2,day,char3)
str_c(year,c("年"),month,c("月"),day,c("日"))
str_c(year,"年",month,"月",day,"日")
str_c(year,month,day, sep="-")
```

```{r}
chineseDate <- c("3月11日","4月5日","2月7日")
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

```{r}
dates
str_replace(dates,"-","月")
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```


```{r}
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
birthday
```


```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```


```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```







